language: python
python:
  - "2.7"
script:
   - coverage run --source='.' ./manage.py test

install:
  - pip install -r requirements.txt

after_success:
  - coveralls

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE invoicing'